## Importing the Libraries

### The below library has many mathematical functions


In [7]:
 import numpy as np

### This below library will help us plot nice charts


In [11]:
 import matplotlib.pyplot as plt


### This below library is to import and manage the datasets

In [12]:
import pandas as pd


### Importing the dataset

In [13]:
dataset=pd.read_csv('data.csv')


In [14]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

### set the working directory, whats on left of the comma are "no of rows" and whats on right of the comma are columns so, : means all the lines

In [16]:
X=dataset.iloc[:, :-1].values

In [18]:
X


array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [19]:
Y=dataset.iloc[:, 3].values


In [20]:
Y


array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

### taking care of the missing data , for any numeric data we need to take the mean of rest of the data and fill it in the missing cell, For this we need a scikit library. the below code also means that SimpleImputer is the class imported sklearn.impute libraries
### to get some info about a class, type the class and then control+I (In Spyder)

In [32]:
from sklearn.impute import SimpleImputer


In [34]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer=imputer.fit(X[:, 1:3])
X[:, 1:3]=imputer.transform(X[:, 1:3])


In [37]:
X


array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

### Now next step is to encode categorical variables



In [38]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [39]:
#labelEncoder_X=LabelEncoder()
#X[:,0]=labelEncoder_X.fit_transform(X[:,0])

### Setting remainder=’passthrough’ will mean that all columns not specified in the list of “transformers” will be passed through without transformation, instead of being dropped.

In [41]:
onehotencoder=OneHotEncoder(categories='auto')
column_transformer=ColumnTransformer([('one_hot_encoder', onehotencoder, [0])], remainder='passthrough')
X=column_transformer.fit_transform(X)

In [42]:
X

array([[0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 1.0, 0.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

### The below is used to convert the output in the X in variable explorer


In [43]:
X = pd.DataFrame(X)       


In [44]:
X


0  1  2  3        4        5
0  0  1  0  0       44    72000
1  1  0  0  1       27    48000
2  1  0  1  0       30    54000
3  1  0  0  1       38    61000
4  1  0  1  0       40  63777.8
5  0  1  0  0       35    58000
6  1  0  0  1  38.7778    52000
7  0  1  0  0       48    79000
8  1  0  1  0       50    83000
9  0  1  0  0       37    67000

In [45]:
labelencoder_Y=LabelEncoder()
Y= labelencoder_Y.fit_transform(Y)  

In [46]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

### Splitting the dataset ino train set and test set  


In [49]:
from sklearn.model_selection import train_test_split


### Random_state can be 0 or 1 or any other integer. It should be the same value if you want to validate your processing over multiple runs of the code. By the way, I have seen random_state=42 used in many official examples of scikit.

the random_state parameter is used for initializing the internal random number generator, which will decide the splitting of data into train and test indices in your case.

In [50]:
X_train, X_test, Y_train, Y_test= train_test_split(X, Y, test_size = 0.2, random_state = 0)


In [54]:
# X_train
#  X_test
# Y_train
# Y_test

array([1, 1, 1, 0, 1, 0, 0, 1])

### Scaling the data 
Only for the training set , while applying the standard scaler we need to fit and then apply but for the test set we no need to fit

In [56]:
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

<span style="color:blue">Do we need to scale the dummy variables</span>
<br>Its already scaled!!!, But it depends on the context

In [60]:
X_train

array([[ 1.        , -1.        ,  2.64575131, -0.77459667,  0.26306757,
         0.12381479],
       [-1.        ,  1.        , -0.37796447, -0.77459667, -0.25350148,
         0.46175632],
       [ 1.        , -1.        , -0.37796447,  1.29099445, -1.97539832,
        -1.53093341],
       [ 1.        , -1.        , -0.37796447,  1.29099445,  0.05261351,
        -1.11141978],
       [-1.        ,  1.        , -0.37796447, -0.77459667,  1.64058505,
         1.7202972 ],
       [ 1.        , -1.        , -0.37796447,  1.29099445, -0.0813118 ,
        -0.16751412],
       [-1.        ,  1.        , -0.37796447, -0.77459667,  0.95182631,
         0.98614835],
       [-1.        ,  1.        , -0.37796447, -0.77459667, -0.59788085,
        -0.48214934]])

<span style="color:blue">Why do we need Feature Scaling</span>
<ul>
<li>So that our algorithm converges faster</li>
<li>Wen plotting the graph the value which is more shouldnt dominate the value which is less</li>
</ul>
We dont need to apply feature scaling on Y because this is a classification problem and the values are limited to just 0 and 1,
but for regression prolem we will need to scale the Y as well